#ifndef QOLYMPUSCAMERA_GLOBAL_H
#define QOLYMPUSCAMERA_GLOBAL_H

#include <QtCore/qglobal.h>


#ifdef QOLYMPUSCAMERA_LIB
# define QOLYMPUSCAMERA_EXPORT Q_DECL_EXPORT
#else
# define QOLYMPUSCAMERA_EXPORT Q_DECL_IMPORT
#endif

#endif // QOLYMPUSCAMERA_GLOBAL_H
